const activityData = [
  {
    name: "Pendaftaran Anggota Sedekah Berjamaah November 2023",
    slug: "pendaftaran-anggota-sedekah-berjamaah-november-2023",
    begin_date: "2023-11-13",
    end_date: "2023-11-30",
    register_begin_date: "2023-11-13",
    register_end_date: "2023-11-30",
    status: "OPENED",
    category_id: 21,
    created_at: "2023-11-13 16:13:38",
    viewer: 0,
    maximum_role_id: 7,
    activityCategory: {
      id: 21,
      name: "Open Recruitment",
    },
    role: {
      id: 5,
      name: "Aktivis",
      shortname: "AKT",
      description: "User Group AKTIVIS adalah aktivis/jamaah yang sudah lulus LMD/LMDN (Latihan Mujtahid Dakwah/Nasional)",
      index: 2,
    },
    banner_url: "https://admin-api-kaderisasi.salmanitb.com/activity_pic/",
    banner_file: {
      id: 994,
      activity_id: 511,
      filename: "1699868183629.jpeg",
    },
  },
  {
    name: "Webinar Closing Kelas Bahasa Salman Batch 6",
    slug: "webinar-closing-kelas-bahasa-salman-batch-6",
    begin_date: "2023-11-12",
    end_date: "2023-11-12",
    register_begin_date: "2023-11-09",
    register_end_date: "2023-11-12",
    status: "CLOSED",
    category_id: 18,
    created_at: "2023-11-09 11:23:47",
    viewer: 0,
    maximum_role_id: 7,
    activityCategory: {
      id: 18,
      name: "Aktualisasi Diri",
    },
    role: {
      id: 4,
      name: "Jamaah",
      shortname: "JA",
      description: "User Group dengan akses sebagai JAMAAH adalah Jamaah yang sudah lulus SSC (Salman Spiritual Camp) atau kegiatan setara",
      index: 1,
    },
    banner_url: "https://admin-api-kaderisasi.salmanitb.com/activity_pic/",
    banner_file: {
      id: 991,
      activity_id: 508,
      filename: "1699509434611.png",
    },
  },
  {
    name: "Open Recruitmen Panitia LMD 224",
    slug: "open-recruitmen-panitia-lmd-224",
    begin_date: "2023-12-22",
    end_date: "2023-12-24",
    register_begin_date: "2023-11-05",
    register_end_date: "2023-11-09",
    status: "CLOSED",
    category_id: 21,
    created_at: "2023-11-05 08:02:02",
    viewer: 0,
    maximum_role_id: 7,
    activityCategory: {
      id: 21,
      name: "Open Recruitment",
    },
    role: {
      id: 6,
      name: "Kader",
      shortname: "KA",
      description: "user group untuk Kader yang belum resmi mengikuti kegiatan bernama SPECTRA (Spiritual Entrepreneurial Civilizer Training)",
      index: 4,
    },
    banner_url: "https://admin-api-kaderisasi.salmanitb.com/activity_pic/",
    banner_file: {
      id: 990,
      activity_id: 507,
      filename: "1699147205822.jpeg",
    },
  },
  {
    name: "Pendaftaran Salman Cendekia Best Presentation: Uncover the Secrets of Your Best Presentations !",
    slug: "pendaftaran-salman-cendekia-best-presentation-uncover-the-secrets-of-your-best-presentations",
    begin_date: "2023-11-05",
    end_date: "2023-11-05",
    register_begin_date: "2023-10-25",
    register_end_date: "2023-11-05",
    status: "CLOSED",
    category_id: 18,
    created_at: "2023-10-25 08:13:19",
    viewer: 0,
    maximum_role_id: 7,
    activityCategory: {
      id: 18,
      name: "Aktualisasi Diri",
    },
    role: {
      id: 4,
      name: "Jamaah",
      shortname: "JA",
      description: "User Group dengan akses sebagai JAMAAH adalah Jamaah yang sudah lulus SSC (Salman Spiritual Camp) atau kegiatan setara",
      index: 1,
    },
    banner_url: "https://admin-api-kaderisasi.salmanitb.com/activity_pic/",
    banner_file: {
      id: 987,
      activity_id: 505,
      filename: "1698196459063.jpeg",
    },
  },
  {
    name: "I-Class Podcast: Mau Berdakwah Lewat Podcast? Iya!",
    slug: "i-class-podcast-mau-berdakwah-lewat-podcast-iya",
    begin_date: "2023-11-04",
    end_date: "2023-11-04",
    register_begin_date: "2023-10-24",
    register_end_date: "2023-11-04",
    status: "CLOSED",
    category_id: 18,
    created_at: "2023-10-24 20:40:40",
    viewer: 0,
    maximum_role_id: 7,
    activityCategory: {
      id: 18,
      name: "Aktualisasi Diri",
    },
    role: {
      id: 4,
      name: "Jamaah",
      shortname: "JA",
      description: "User Group dengan akses sebagai JAMAAH adalah Jamaah yang sudah lulus SSC (Salman Spiritual Camp) atau kegiatan setara",
      index: 1,
    },
    banner_url: "https://admin-api-kaderisasi.salmanitb.com/activity_pic/",
    banner_file: {
      id: 984,
      activity_id: 504,
      filename: "1698155835726.jpeg",
    },
  },
  {
    name: "PENDAFTARAN PESERTA TUTORIAL STUDENT CARE - SMSTR 1 2023/2024",
    slug: "pendaftaran-peserta-tutorial-student-care-smstr-1-2023-2024",
    begin_date: "2023-08-10",
    end_date: "2023-12-19",
    register_begin_date: "2023-08-10",
    register_end_date: "2023-12-10",
    status: "OPENED",
    category_id: 18,
    created_at: "2023-08-10 08:17:34",
    viewer: 0,
    maximum_role_id: 7,
    activityCategory: {
      id: 18,
      name: "Aktualisasi Diri",
    },
    role: {
      id: 4,
      name: "Jamaah",
      shortname: "JA",
      description: "User Group dengan akses sebagai JAMAAH adalah Jamaah yang sudah lulus SSC (Salman Spiritual Camp) atau kegiatan setara",
      index: 1,
    },
    banner_url: "https://admin-api-kaderisasi.salmanitb.com/activity_pic/",
    banner_file: {
      id: 864,
      activity_id: 463,
      filename: "1691723770840.png",
    },
  },
];

export default activityData;
